/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment4;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {
  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    Member member = new Member("Jacob", "j00cwa@gmail.com", "123456");

    Motorboat boatOne = new Motorboat("test", "Motorboat", 20, 200);
    Motorboat boatTwo = new Motorboat("testTwo", "Motorboat", 30, 250);
    Motorboat boatThree = new Motorboat("testThree", "Motorboat", 40, 170);

    member.addBoat(boatOne);
    member.addBoat(boatTwo);
    member.addBoat(boatThree);

    member.showMemberInfo();
  }
}
